# Generated by Django 4.2.16 on 2024-11-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_options_and_more'),
    ]

    operations = []
